services:
  url-shortener:
    build: .
    ports:
      - "${EXPOSED_PORT}:${INTERNAL_PORT}"
    env_file:
      - .env
    environment:
      REDIS_ADDR: ${REDIS_ADDR}
      INTERNAL_PORT: ${INTERNAL_PORT}
      INTERNAL_ADDR: ${INTERNAL_ADDR}
